#!/bin/bash
#
# Trigger Jenkins jobs
#
declare jenkins_url='https://ehrzgux506.etk.extern.eu.ericsson.se/git/notifyCommit'
declare scm_url='ssh://jenkins@ehrzgux505.etk.extern.eu.ericsson.se/srv/git/etkc.git'
curl -k "${jenkins_url}"?url="${scm_url}"&branches="${refname}"&sha1="${newrev}"
